In [2]:
import numpy as np

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
np.full(10,2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [28]:
arr = np.array([[1,2,3,4,5],[1,4,2,3,9]])

In [12]:
a = np.array([1,2,3,4,5])

In [15]:
a[2] = 10

In [16]:
arr[1][3]

3

In [18]:
a

array([ 1,  2, 10,  4,  5])

In [21]:
np.arange(3,10,.1)

array([3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2,
       4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5,
       5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8,
       6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7, 7.8, 7.9, 8. , 8.1,
       8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. , 9.1, 9.2, 9.3, 9.4,
       9.5, 9.6, 9.7, 9.8, 9.9])

In [24]:
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [26]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [30]:
arr[1,:]

array([1, 4, 2, 3, 9])

In [36]:
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [37]:
np.random.seed(2)
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [39]:
np.random.seed(2)
np.random.randint(low=0,high=100,size=(5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

In [41]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [42]:
a+1

array([1, 2, 3, 4, 5])

In [43]:
a*2

array([0, 2, 4, 6, 8])

In [49]:
b= (a/2+10)**2
b

array([100.  , 110.25, 121.  , 132.25, 144.  ])

In [48]:
a+b

array([100.  , 111.25, 123.  , 135.25, 148.  ])

In [50]:
a*b

array([  0.  , 110.25, 242.  , 396.75, 576.  ])

In [51]:
a <=b

array([ True,  True,  True,  True,  True])

In [53]:
a[b>a]

array([0, 1, 2, 3, 4])

In [54]:
a.sum()

10

In [55]:
b.std()

15.561972882639271

In [57]:
np.dot(a,b)

1325.0

In [58]:
a.shape[0]

5

In [59]:
def vector_multiplication(a,b):
    assert a.shape[0]== b.shape[0]

    n = a.shape[0]

    result = 0
    for i in range(n):
        result += a[i]*b[i]
    return result    

In [60]:
vector_multiplication(a,b)

1325.0

In [61]:
arr

array([[1, 2, 3, 4, 5],
       [1, 4, 2, 3, 9]])

In [62]:
a

array([0, 1, 2, 3, 4])

In [63]:
np.dot(arr,a)

array([40, 53])

In [70]:
def matrix_multi(U,v):
    assert U.shape[1]== v.shape[0]
    num_rows = U.shape[0]
    result = np.zeros(num_rows)

    for i in range(num_rows):
        result[i] += vector_multiplication(U[i],v)
    return result

In [71]:
matrix_multi(arr,a)

array([40., 53.])

In [72]:
arr.dot(a)

array([40, 53])

In [84]:
arr = np.array([[1, 2, 3],
       [1, 4, 2],[2,3,4]])

In [86]:
arr.dot(arr)

array([[ 9, 19, 19],
       [ 9, 24, 19],
       [13, 28, 28]])

In [92]:
m = np.eye(3)

In [90]:
m

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [94]:
m.dot(arr)

array([[1., 2., 3.],
       [1., 4., 2.],
       [2., 3., 4.]])

In [97]:
i = np.linalg.inv(arr)

In [99]:
i.dot(arr)

array([[ 1.00000000e+00,  4.44089210e-16,  0.00000000e+00],
       [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00, -1.11022302e-16,  1.00000000e+00]])